Repository nextjes/tratics, pull requests merged in 2025-03, with the labels that each got.

#5 상태 관리 구성 및 디렉터리 수정 적용
  eunjeong/app/client/images/computer-monitor-svgrepo-com.svg
  eunjeong/app/client/images/server-svgrepo-com.svg
  eunjeong/app/client/lib/constants.ts
  eunjeong/app/client/lib/utils.ts
  eunjeong/app/client/main/Header.tsx
  eunjeong/app/client/main/Main.tsx
  eunjeong/app/client/main/Section.tsx
  eunjeong/app/client/ui/button.tsx
  eunjeong/app/client/ui/input.tsx
  eunjeong/app/engine/DummyNode.ts
  eunjeong/app/engine/SimulationClock.ts
  eunjeong/app/engine/index.ts
  eunjeong/app/main/Section.tsx
  eunjeong/app/routes/home.tsx
  eunjeong/app/store/memory.ts
  eunjeong/package.json
  eunjeong/tsconfig.json
  eunjeong/yarn.lock
Labels: enhancement

#7 Tratics#6
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  app/app.css
  app/client/images/computer-monitor-svgrepo-com.svg
  app/client/images/server-svgrepo-com.svg
  app/client/lib/constants.ts
  app/client/lib/utils.ts
  app/client/main/Header.tsx
  app/client/main/Main.tsx
  app/client/main/Section.tsx
  app/client/ui/button.tsx
  app/client/ui/input.tsx
  app/engine/DummyNode.ts
  app/engine/SimulationClock.ts
  app/engine/index.ts
  app/root.tsx
  app/routes.ts
  app/routes/home.tsx
  app/store/memory.ts
  components.json
  eslint.config.js
  eunjeong/.gitignore
  eunjeong/README.md
  joowan/index.html
  joowan/package-lock.json
  joowan/package.json
  joowan/src/App.tsx
  joowan/src/SimulationEngine/DummyNode.ts
  joowan/src/SimulationEngine/SimulationClock.ts
  joowan/src/SimulationEngine/main.ts
  joowan/src/index.tsx
  joowan/tsconfig.json
  joowan/vite.config.ts
  package.json
  public/favicon.ico
  react-router.config.ts
  svg.d.ts
  tsconfig.json
  vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: enhancement

#9 도메인 스키마 정의
  app/client/main/Main.tsx
  app/client/main/Section.tsx
  app/engine/DummyNode.ts
  app/engine/Node.ts
  app/engine/SimulationClock.ts
  app/engine/entryPoints.ts
  app/store/memory.ts
Labels: enhancement

#11 테스트 워크플로우 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/update-issue-status.yml
  README.md
  package.json
  tests/engine/node/reset.test.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#15 issue:#12/ `SimulationClock` 단위 테스트 추가
  app/engine/SimulationClock.ts
  app/engine/entryPoints.ts
  app/engine/index.ts
  app/engine/term/index.ts
  app/engine/term/time.ts
  tests/engine/simulationClock/simulationClock.test.ts
  tests/engine/term/time/milliSecond.test.ts
  tests/engine/term/time/second.test.ts
  vitest.config.ts
Labels: enhancement

#19 issue:#16/`Dashboard` 객체 초안 팩토리 메소드 추가
  app/engine/clock.ts
  app/engine/dashboard.ts
  app/engine/entryPoints.ts
  app/engine/updatable.ts
  tests/engine/clock/simulationClock.test.ts
  tests/engine/dashboard/dashboard.test.ts
  tests/engine/updatable/reset.test.ts
Labels: enhancement

#21 issue:#20/ 존재하지 않는 경로 참조 오류 수정
  app/engine/entryPoints.ts
Labels: bug

#23 issue:#17/ `Node` 클래스 단위 테스트 추가
  app/engine/entryPoints.ts
  app/engine/updatable.ts
  app/engine/updatable/index.ts
  app/engine/updatable/node.ts
  tests/engine/updatable/node.test.ts
  tests/engine/updatable/reset.test.ts
Labels: enhancement

#24 issue:#18/ Dashboard를 Scene으로 전환
  app/engine/dashboard.ts
  app/engine/entryPoints.ts
  app/engine/scene.ts
  app/engine/updatable/clock.ts
  app/engine/updatable/index.ts
  app/engine/updatable/node.ts
  app/engine/updatable/temporal.ts
  tests/engine/dashboard/dashboard.test.ts
  tests/engine/updatable/node.test.ts
  tests/engine/updatable/simulationClock.test.ts
Labels: enhancement

#27 issue:#22/ `Task` 개념 추가
  app/client/main/Section.tsx
  app/engine/entryPoints.ts
  app/engine/error.ts
  app/engine/index.ts
  app/engine/scene.ts
  app/engine/term/constants.ts
  app/engine/term/index.ts
  app/engine/updatable/clock.ts
  app/engine/updatable/index.ts
  app/engine/updatable/node.ts
  app/engine/updatable/task.ts
  app/engine/updatable/temporal.ts
  tests/engine/updatable/node.test.ts
  tests/engine/updatable/task.test.ts
Labels: enhancement

#29 issue:#28/ 시뮬레이션 엔진 내부에서 milli second 단위만 사용하도록 수정
  app/engine/entryPoints.ts
  app/engine/term/index.ts
  app/engine/term/time.ts
  app/engine/updatable/clock.ts
  app/engine/updatable/node.ts
  app/engine/updatable/task.ts
  tests/engine/term/time/milliSecond.test.ts
  tests/engine/updatable/node.test.ts
  tests/engine/updatable/simulationClock.test.ts
  tests/engine/updatable/task.test.ts
Labels: enhancement

#30 백엔드 코드 개선
  app/client/main/Section.tsx
  app/engine/core/index.ts
  app/engine/core/network/index.ts
  app/engine/core/network/link.ts
  app/engine/core/network/message.ts
  app/engine/core/simulation/index.ts
  app/engine/core/simulation/scene.ts
  app/engine/core/simulation/simulationConfig.ts
  app/engine/core/simulation/simulationEngine.ts
  app/engine/core/topology/index.ts
  app/engine/core/topology/networkTopology.ts
  app/engine/core/topology/topologyBuilder.ts
  app/engine/core/updatable/clock.ts
  app/engine/core/updatable/index.ts
  app/engine/core/updatable/node.ts
  app/engine/core/updatable/task.ts
  app/engine/entryPoints.ts
  app/engine/error.ts
  app/engine/index.ts
  app/engine/interfaces/index.ts
  app/engine/interfaces/publishable.ts
  app/engine/interfaces/temporal.ts
  app/engine/scene.ts
  app/engine/term/constants.ts
  app/engine/term/identifier.ts
  app/engine/term/index.ts
  app/engine/term/position.ts
  app/engine/term/time.ts
  app/engine/updatable/clock.ts
  app/engine/updatable/index.ts
  app/engine/updatable/node.ts
  app/engine/updatable/task.ts
  app/engine/updatable/temporal.ts
  app/store/memory.ts
  tests/engine/core/clock.test.ts
  tests/engine/core/core.test.ts
  tests/engine/core/node.test.ts
  tests/engine/core/task.test.ts
  tests/engine/network/link.test.ts
  tests/engine/network/message.test.ts
  tests/engine/term/identifier/identifier.test.ts
  tests/engine/term/position/postition.test.ts
  tests/engine/term/time/milliSecond.test.ts
  tests/engine/term/time/second.test.ts
  tests/engine/topology/networkTopology.test.ts
  tests/engine/topology/topologyBuilder.test.ts
  tests/engine/updatable/node.test.ts
  tests/engine/updatable/simulationClock.test.ts
  tests/engine/updatable/task.test.ts
Labels: enhancement

#36 issue: #35/ 프로젝트 아키텍처 및 컨벤션 문서 리드미에 추가
  README.md
Labels: documentation
